routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------|
*/

// Home
Route::name('home')->get('/', 'Front\PostController@index');

// Contact
Route::resource('contacts', 'Front\ContactController', ['only' => ['create', 'store']]);

// Posts and comments
Route::prefix('posts')->namespace('Front')->group(function () {
    Route::name('posts.display')->get('{slug}', 'PostController@show');
    Route::name('posts.search')->get('', 'PostController@search');
    Route::name('posts.comments.store')->post('{post}/comments', 'CommentController@store');
    Route::name('posts.comments.comments.store')->post('{post}/comments/{comment}/comments', 'CommentController@store');
    Route::name('posts.comments')->get('{post}/comments/{page}', 'CommentController@comments');
});

Route::resource('comments', 'Front\CommentController', [
    'only' => ['update', 'destroy'],
    'names' => ['destroy' => 'front.comments.destroy']
]);

Route::name('category')->get('category/{category}', 'Front\PostController@category');

// Authentification
Auth::routes();


/*
|--------------------------------------------------------------------------
| Backend
|--------------------------------------------------------------------------|
*/

Route::prefix('admin')->namespace('Back')->group(function () {
    

    Route::middleware('redac')->group(function () {

        Route::name('admin')->get('/', 'AdminController@index');

        // Posts
        Route::name('posts.seen')->put('posts/seen/{post}', 'PostController@updateSeen')->middleware('can:manage,post');
        Route::name('posts.active')->put('posts/active/{post}/{status?}', 'PostController@updateActive')->middleware('can:manage,post');
        Route::resource('posts', 'PostController');

        // Notifications
        Route::name('notifications.index')->get('notifications/{user}', 'NotificationController@index');
        Route::name('notifications.update')->put('notifications/{notification}', 'NotificationController@update');

        // Medias
        Route::view('medias', 'back.medias')->name('medias.index');

        // Sacerdotes
        Route::resource('sacerdotes', 'SacerdoteController', ['except' => 'show']);

        // Eucaristias
        Route::resource('eucaristias', 'EucaristiaController', ['except' => 'show']);
        
        // Confirmaciones
        Route::resource('confirms', 'ConfirmController', ['except' => 'show']);
        Route::name('confirms.export_pdf')->get('/confirms/pdf/{confirm}','ConfirmController@export_pdf');

        // Bautizos
        Route::resource('bautizos', 'BautizoController', ['except' => 'show']);
        Route::name('bautizos.export_pdf')->get('/bautizos/pdf/{bautizo}','BautizoController@export_pdf');

        // Defunciones
        Route::resource('defuncs', 'DefuncController', ['except' => 'show']);
        Route::name('defuncs.export_pdf')->get('/defuncs/pdf/{defunc}','DefuncController@export_pdf');
        
        // Matrimonios
        Route::resource('matrimonios', 'MatrimonioController', ['except' => 'show']);
        Route::name('matrimonios.export_pdf')->get('/matrimonios/pdf/{matrimonio}','MatrimonioController@export_pdf');

    });

    Route::middleware('admin')->group(function () {

        // Users
        Route::name('users.seen')->put('users/seen/{user}', 'UserController@updateSeen');
        Route::name('users.valid')->put('users/valid/{user}', 'UserController@updateValid');
        Route::resource('users', 'UserController', ['only' => [
            'index', 'edit', 'update', 'destroy'
        ]]);

        // Categories
        Route::resource('categories', 'CategoryController', ['except' => 'show']);
        
        

        // Contacts
        Route::name('contacts.seen')->put('contacts/seen/{contact}', 'ContactController@updateSeen');
        Route::resource('contacts', 'ContactController', ['only' => [
            'index', 'destroy'
        ]]);

        // Comments
        Route::name('comments.seen')->put('comments/seen/{comment}', 'CommentController@updateSeen');
        Route::resource('comments', 'CommentController', ['only' => [
            'index', 'destroy'
        ]]);

        // Settings
        Route::name('settings.edit')->get('settings', 'AdminController@settingsEdit');
        Route::name('settings.update')->put('settings', 'AdminController@settingsUpdate');

    });

});

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\ {
    Http\Controllers\Controller,
    Http\Requests\SettingsRequest,
    Repositories\ConfigAppRepository,
    Repositories\EnvRepository,
    Services\PannelAdmin
};
use Illuminate\Support\Facades\Artisan;

class AdminController extends Controller
{
    /**
     * Show the admin dashboard.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $pannels = [];

        foreach (config('pannels') as $pannel) {

            $panelAdmin = new PannelAdmin($pannel);

            if ($panelAdmin->nbr) {
                $pannels[] = $panelAdmin;
            }
        }

        return view('back.index', compact('pannels'));
    }

    /**
     * Show the settings page
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function settingsEdit()
    {
        $actualLocale = config ('app.locale');
        $locales = locales();

        $actualDriver = env('MAIL_DRIVER');
        $drivers = [
            'smtp' =>'SMTP',
            'mail' => 'PHP'
        ];

        $actualTimezone = config ('app.timezone');
        $timezones = timezones ();

        $actualCacheDriver = env('CACHE_DRIVER');
        $caches = ['apc', 'array', 'database', 'file', 'memcached', 'redis'];

        $actualConnection = env('DB_CONNECTION');
        $connections = ['mysql', 'sqlite', 'pgsql'];

        return view('back.settings', compact (
            'locales',
            'actualLocale',
            'drivers',
            'actualDriver',
            'timezones',
            'actualTimezone',
            'caches',
            'actualCacheDriver',
            'connections',
            'actualConnection'
        ));
    }

    /**
     * Update settings
     *
     * @param \App\Http\Requests\SettingsRequest $request
     * @param \App\Repositories\ConfigAppRepository $appRepository
     * @param \App\Repositories\EnvRepository $envRepository
     * @return \Illuminate\Http\RedirectResponse
     * @internal param ConfigAppRepository $repository
     */
    public function settingsUpdate(
        SettingsRequest $request,
        ConfigAppRepository $appRepository,
        EnvRepository $envRepository)
    {
        $inputs = $request->except ('_method', '_token', 'page');

        $envRepository->update (array_filter($inputs, function ($key) {
            return strpos ($key, '_');
        }, ARRAY_FILTER_USE_KEY ));

        $appRepository->update(array_filter($inputs, function ($key) {
            return !strpos ($key, '_');
        }, ARRAY_FILTER_USE_KEY ));

        $cache = $this->checkCache () ? ' ' . __('Config cache has been updated.'): '';

        $request->session ()->flash ('ok', __('Settings have been successfully saved. ') . $cache);

        return redirect()->route('settings.edit', ['page' => $request->page]);
    }

    /**
     * Check and refresh cache if exists
     *
     * @return bool
     */
    protected function checkCache ()
    {
        if (file_exists (app()->getCachedConfigPath ())) {
            Artisan::call('config:clear');
            Artisan::call('config:cache');
            return true;
        }
        return false;
    }
}

app/Http/Controllers/Back/BautizoController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use PDF;
use Carbon\Carbon;
use App\ {
    Http\Controllers\Controller,
    Http\Requests\BautizoRequest,
    Models\Bautizo,
    Models\Sacerdote,
};


class BautizoController extends Controller
{
    /**
     * Display a listing of the bautizos.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->old('search');
        $type = $request->old('type');
        
        $bautizos = Bautizo::orderBy('id', 'DESC')
            ->search($type, $search)
            ->paginate(8);

        return view('back.bautizos.index', compact ('bautizos', 'search', 'type'));
    }

    /**
     * Show the form for creating a new bautizo.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sacerdotes = Sacerdote::all();
        return view('back.bautizos.create', compact ('sacerdotes'));
    }

    /**
     * Store a newly created bautizo in storage.
     *
     * @param  \App\Http\Requests\BautizoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BautizoRequest $request)
    {
        Bautizo::create($request->all());

        return redirect(route('bautizos.index'))->with('bautizo-ok', __('El bautizo ha sido creado exitosamente.'));
    }

    /**
     * Show the form for editing the specified bautizo.
     *
     * @param  \App\Models\Bautizo  $bautizo
     * @return \Illuminate\Http\Response
     */
    public function edit(Bautizo $bautizo)
    {
        $sacerdotes = Sacerdote::all();
        return view('back.bautizos.edit', compact ('bautizo', 'sacerdotes'));
    }

    /**
     * Update the specified bautizo in storage.
     *
     * @param  \App\Http\Requests\BautizoRequest  $request
     * @param  \App\Models\Bautizo  $bautizo
     * @return \Illuminate\Http\Response
     */
    public function update(BautizoRequest $request, Bautizo $bautizo)
    {
        $bautizo->update($request->all());

        return redirect(route('bautizos.index'))->with('bautizo-ok', __('El bautizo ha sido actualizado exitosamente.'));
    }

    /**
     * Remove the specified bautizo from storage.
     *
     * @param  \App\Models\bautizo  $bautizo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bautizo $bautizo)
    {
        $bautizo->delete ();

        return response ()->json ();
    }

    public function export_pdf(Bautizo $bautizo)
    {
        $pdf = PDF::loadView('back.bautizos.certificado_pdf', compact('bautizo'));
        return $pdf->download('bautizo_'.Carbon::now().'.pdf');
    }
}

app/Http/Controllers/Back/CategoryController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use App\ {
    Http\Controllers\Controller,
    Http\Requests\CategoryRequest,
    Models\Category
};

class CategoryController extends Controller
{
    /**
     * Display a listing of the categories.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::oldest('title')->withCount('posts')->get();

        return view('back.categories.index', compact ('categories'));
    }

    /**
     * Show the form for creating a new categorie.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back.categories.create');
    }

    /**
     * Store a newly created categorie in storage.
     *
     * @param  \App\Http\Requests\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());

        return redirect(route('categories.index'))->with('category-ok', __('The category has been successfully created'));
    }

    /**
     * Show the form for editing the specified categorie.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('back.categories.edit', compact ('category'));
    }

    /**
     * Update the specified categorie in storage.
     *
     * @param  \App\Http\Requests\CategoryRequest  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());

        return redirect(route('categories.index'))->with('category-ok', __('The category has been successfully updated'));
    }

    /**
     * Remove the specified categorie from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete ();

        return response ()->json ();
    }
}

app/Http/Controllers/Back/CommentController.php
<?php

namespace App\Http\Controllers\Back;

use App\ {
    Models\Comment,
    Repositories\CommentRepository,
    Http\Controllers\Controller
};

class CommentController extends Controller
{
    use Indexable;

    /**
     * Create a new CommentController instance.
     *
     * @param  \App\Repositories\CommentRepository $repository
     */
    public function __construct(CommentRepository $repository)
    {
        $this->repository = $repository;

        $this->table = 'comments';
    }

    /**
     * Update "new" field for comment.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function updateSeen(Comment $comment)
    {
        $comment->ingoing->delete ();

        return response ()->json ();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete ();

        return response ()->json ();
    }
}

app/Http/Controllers/Back/ConfirmController.php
<?php

namespace App\Http\Controllers\Back;

use Illuminate\Http\Request;
use PDF;
use Carbon\Carbon;
use App\ {
    Http\Controllers\Controller,
    Http\Requests\ConfirmRequest,
    Models\Confirm,
    Models\Sacerdote,
};

class ConfirmController extends Controller
{
    /**
     * Display a listing of the categories.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->old('search');
        $type = $request->old('type');

        $confirms = Confirm::orderBy('id', 'DESC')
            ->search($type, $search)
            ->paginate(8);

        return view('back.confirmaciones.index', compact ('confirms', 'search', 'type'));
    }

    /**
     * Show the form for creating a new eucaristia.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sacerdotes = Sacerdote::all();
        return view('back.confirmaciones.create', compact ('sacerdotes'));
    }

    /**
     * Store a newly created eucaristia in storage.
     *
     * @param  \App\Http\Requests\ConfirmRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ConfirmRequest $request)
    {
        Confirm::create($request->all());

        return redirect(route('confirms.index'))->with('confirmacion-ok', __('La confirmación ha sido creada exitosamente.'));
    }

    /**
     * Show the form for editing the specified eucaristia.
     *
     * @param  \App\Models\Confirm  $confirm
     * @return \Illuminate\Http\Response
     */
    public function edit(Confirm $confirm)
    {
        $sacerdotes = Sacerdote::all();
        return view('back.confirmaciones.edit', compact ('confirm', 'sacerdotes'));
    }

    /**
     * Update the specified eucaristia in storage.
     *
     * @param  \App\Http\Requests\ConfirmRequest  $request
     * @param  \App\Models\Confirm  $confirm
     * @return \Illuminate\Http\Response
     */
    public function update(ConfirmRequest $request, Confirm $confirm)
    {
        $confirm->update($request->all());

        return redirect(route('confirms.index'))->with('confirmacion-ok', __('La confirmación ha sido actualizada exitosamente.'));
    }

    /**
     * Remove the specified eucaristia from storage.
     *
     * @param  \App\Models\Confirm  $confirm
     * @return \Illuminate\Http\Response
     */
    public function destroy(Confirm $confirm)
    {
        $confirm->delete ();

        return response ()->json ();
    }

    public function export_pdf(Confirm $confirm)
    {
        $pdf = PDF::loadView('back.confirmaciones.certificado_pdf', compact('confirm'));
        return $pdf->download('confirmacion_'.Carbon::now().'.pdf');
    }
}

resources/views/back/eucaristias/create.blade.php
@extends('back.eucaristias.template')

@section('form-open')
    <form method="post" action="{{ route('eucaristias.store') }}">
@endsection

resources/views/back/eucaristias/edit.blade.php
@extends('back.eucaristias.template')

@section('form-open')
    <form method="post" action="{{ route('eucaristias.update', [$eucaristia->id]) }}">
        {{ method_field('PUT') }}
@endsection

resources/views/back/eucaristias/index.blade.php
@extends('back.layout')

@section('css')
    <link rel="stylesheet" href="//cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css">
    <style>
        input, th span {
            cursor: pointer;
        }
        .pagination>li>a, .pagination>li>span {
            padding: 5px 10px;
            font-size: 12px;
            line-height: 1.5;
        }
        .pagination{
            margin: 0 !important;
        }
    </style>
@endsection

@section('button')
    <a class="btn btn-primary" href="{{ route('eucaristias.create') }}">@lang('Nueva Eucaristía')</a>
@endsection

@section('main')

    <form method="post" action="{{ route('eucaristias.index') }}" class="navbar-form pull-right">
        {{ csrf_field() }}

        <input type="radio" name="type" value="libro" checked> @lang('Libro')&nbsp;&nbsp;
        <input type="radio" name="type" value="folio" {{ $type == "folio" ? 'checked' : '' }}> @lang('Folio')&nbsp;&nbsp;
        <input type="radio" name="type" value="numero" {{ $type == "numero" ? 'checked' : '' }}> @lang('Numero')&nbsp;&nbsp;
        <input type="radio" name="type" value="nombres" {{ $type == "nombres" ? 'checked' : '' }}> @lang('Nombres')&nbsp;&nbsp;
        <input type="radio" name="type" value="apellidos" {{ $type == "apellidos" ? 'checked' : '' }}> @lang('Apellidos')&nbsp;&nbsp;
        <input type="radio" name="type" value="fecha_expedicion" {{ $type == "fecha_expedicion" ? 'checked' : '' }}> @lang('Fecha de Expedicion')&nbsp;&nbsp;
        
        <div class="input-group"> 
            <input type="text" class="form-control" name="search" placeholder="Busqueda"> 
                <span class="input-group-btn"> 
                <button type="submit" class="btn btn-default"> 
                    <span class="fa fa-search"></span> 
                </button> 
                <button type="submit" class="btn btn-default"> 
                    <span class="fa fa-refresh"></span> 
                </button> 
            </span> 
        </div> 
    </form>

    <div class="navbar-form pull-left">
        {{ isset($search) ? 'Búsqueda: '.$search : '' }}
    </div>

    <div class="row">
        <div class="col-md-12">
            @if (session('eucaristia-ok'))
                @component('back.components.alert')
                    @slot('type')
                        success
                    @endslot
                    {!! session('eucaristia-ok') !!}
                @endcomponent
            @endif
            <div class="box">
                <div class="box-header with-border">
                    <div id="spinner" class="text-center"></div>
                </div>
                <div class="box-body table-responsive">
                    <table id="users" class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>@lang('libro')</th>
                            <th>@lang('Folio')</th>
                            <th>@lang('Numero')</th>
                            <th>@lang('Parroquia')</th>
                            <th>@lang('Nombres')</th>
                            <th>@lang('Apellidos')</th>
                            <th>@lang('Sacerdote que firma')</th>
                            <th>@lang('Fecha de Nacimiento')</th>
                            <th>@lang('Fecha de Expedición')</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        
                        <tbody id="pannel">
                            @include('back.eucaristias.table', compact('eucaristias'))
                        </tbody>
                    </table>
                </div>

                <div id="pagination" class="box-footer">
                    <div class="pagination-sm no-margin pull-right">
                        {{ $eucaristias->links() }}
                    </div>
                </div>
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

@endsection

@section('js')
    <script src="{{ asset('adminlte/js/back.js') }}"></script>
    <script>

        var eucaristia = (function () {

            var onReady = function () {
                $('#pannel').on('click', 'td a.btn-danger', function (event) {
                    var that = $(this)
                    event.preventDefault()
                    swal({
                        title: '@lang('Quieres eliminar esta eucaristía?')',
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: '#DD6B55',
                        confirmButtonText: '@lang('Si')',
                        cancelButtonText: '@lang('No')'
                    }).then(function () {
                        back.spin()
                        $.ajax({
                            url: that.attr('href'),
                            type: 'DELETE'
                        })
                            .done(function () {
                                that.parents('tr').remove()
                                back.unSpin()
                            })
                            .fail(function () {
                                back.fail('@lang('Parece que hay un problema con el servidor...')')
                            }
                        )
                    })
                })
            }

            return {
                onReady: onReady
            }

        })()

        $(document).ready(eucaristia.onReady)

    </script>
@endsection

resources/views/back/eucaristias/table.blade.php
@foreach($eucaristias as $eucaristia)
    <tr>
        <td>{{ $eucaristia->libro }}</td>
        <td>{{ $eucaristia->folio }}</td>
        <td>{{ $eucaristia->numero }}</td>
        <td>{{ $eucaristia->parroquia }}</td>
        <td>{{ $eucaristia->nombres }}</td>
        <td>{{ $eucaristia->apellidos }}</td>
        <td>{{ $eucaristia->sacerdoteFirma->nombre }}</td>
        <td>{{ $eucaristia->fecha_nacimiento }}</td>
        <td>{{ $eucaristia->fecha_expedicion }}</td>
        <td><a class="btn btn-warning btn-xs btn-block" href="{{ route('eucaristias.edit', [$eucaristia->id]) }}" role="button" title="@lang('Editar')"><span class="fa fa-edit"></span></a></td>
        <td><a class="btn btn-danger btn-xs btn-block" href="{{ route('eucaristias.destroy', [$eucaristia->id]) }}" role="button" title="@lang('Eliminar')"><span class="fa fa-remove"></span></a></td>
    </tr>
@endforeach